---
name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test distribution
    needs: build
    strategy:
      matrix:
        perl-version:
          - "5.22"
    container:
      image: perl:${{ matrix.perl-version }}
      env:
        - DEPLOYMENT_PERL_VERSION=5.22
        - DEVEL_COVER_OPTIONS="-ignore,^local/"
        - CPAN_RESOLVER=snapshot
    steps:
      - name: Install deps
        run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
      - name: Run Tests
        if: success()
        run: prove -lvr --jobs 2 t
