---
name: test

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test distribution
    strategy:
      matrix:
        perl-version:
          - "5.22"
    container:
      image: perl:${{ matrix.perl-version }}
      env:
        DEPLOYMENT_PERL_VERSION: 5.22
        DEVEL_COVER_OPTIONS: "-ignore,^local/"
        CPAN_RESOLVER: snapshot
    steps:
      - uses: actions/checkout@v1
      - name: Install Carton
        run: curl -sL https://git.io/cpm | perl - install Carton --show-build-log-on-failure
      - name: Install deps
        run: curl -sL https://git.io/cpm | perl - install --cpanfile cpanfile --show-build-log-on-failure
      - name: Run Tests
        if: success()
        run: carton exec prove -lvr --jobs 2 t
